# -*- coding: utf-8 -*-
"""Data_Ananlytics lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iShv_puoLFoSZDmfabTKTXoGOJKqj7tl
"""

#Q1
file = open('/content/bank.csv','r')
data=file.readlines()
header = file.readline()
for item in file:
    print(item.strip().split(","))

#Q2
file = open('/content/bank.csv','r')
data = file.readline().strip().split(",")
print(data)

#Q3
file = open('/content/bank.csv','r')
def marital():
    married=0
    single=0

    for item in data:
        count=item.split(";")
        marital=count[2].strip('"')
        if marital=="married":
            married+=1
        else:
            single+=1
    print(married)
    print(single)

marital()

def prepare_age_histogram(data):
    # Prepare a histogram for age
    ages = []
    for line in data[1:]:
        customer = line.strip().split(';')
        age = int(customer[0])  # Assuming age column is at index 3
        ages.append(age)

    # Divide ages into classes of interval 10
    age_classes = {}
    for age in ages:
        age_class = age // 10 * 10
        if age_class in age_classes:
            age_classes[age_class] += 1
        else:
            age_classes[age_class] = 1

    print("Histogram for age:")
    for age_class, count in age_classes.items():
        print(f"{age_class}-{age_class + 9}: {'|' * count}")

prepare_age_histogram(data)

